### PR TITLE
Look into the correct blacklist path for react-native 0.52 and onwards

### LINKED ISSUE #22: Doesn't work with react-native >=0.52
The output is:

   > $ whack run start
   > [whackage] init /Users/.../client-blocks -> node_modules/client-blocks
   > 
   > &gt; react-native start "--config" "/usr/local/lib/node_modules/whackage/src/packager/rn-cli.config.js"
   >
   > Scanning folders for symlinks in /Users/.../app/node_modules (19ms)
   >
   > Cannot find module '/Users/.../app/node_modules/react-native/packager/blacklist'

It looks like they renamed metro-bundler to metro [https://github.com/facebook/react-native/commit/654fed46f49b5002096ff55c2e8523af48b22c24](https://github.com/facebook/react-native/commit/654fed46f49b5002096ff55c2e8523af48b22c24)

### PR DESCRIPTION
**Pull request by poison**
(See https://github.com/facebook/react-native/commit/654fed46f49b5002096ff55c2e8523af48b22c24)

Fixes #22

### CODE REVIEW

**Review by kitten — APPROVED** [review]
lgtm :+1:

**Review by jpdriver — APPROVED** [review]
@kitten merge me!

**Review by treyp — APPROVED** [review]
working again for me on React Native 0.52 👍

**Comment by jevakallio** [comment]
Merged and released as 1.3.0. Thanks everyone 🎉
