### ISSUE TITLE
Doesn't work with react-native >=0.52

### ISSUE THREAD

**Issue by poison** [FormidableLabs/whackage#22]
The output is:

   > $ whack run start
   > [whackage] init /Users/.../client-blocks -> node_modules/client-blocks
   > 
   > &gt; react-native start "--config" "/usr/local/lib/node_modules/whackage/src/packager/rn-cli.config.js"
   >
   > Scanning folders for symlinks in /Users/.../app/node_modules (19ms)
   >
   > Cannot find module '/Users/.../app/node_modules/react-native/packager/blacklist'

It looks like they renamed metro-bundler to metro [https://github.com/facebook/react-native/commit/654fed46f49b5002096ff55c2e8523af48b22c24](https://github.com/facebook/react-native/commit/654fed46f49b5002096ff55c2e8523af48b22c24)
